name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run build
        run: npm run build

      - name: Move build folder to docs
        run: mv build docs

      - name: Config git author
        run: |
          git config --global user.name "Link Strifer"
          git config --global user.email "linkstrifer@users.noreply.github.com"

      - name: Commit generated files
        run: |
          git status
          git add .
          git commit -am "Automated commit: Generated doc files"

      - name: Git push
        run: git push
